"""empty message

Revision ID: 06ab645cb593
Revises: 
Create Date: 2017-01-27 09:07:46.799311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ab645cb593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('InstagramResult', 'query')
    op.add_column('Result', sa.Column('search_name', sa.String(length=500), nullable=True))
    op.drop_column('Result', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Result', sa.Column('query', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Result', 'search_name')
    op.add_column('InstagramResult', sa.Column('query', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
