"""empty message

Revision ID: 10c63898a94e
Revises: None
Create Date: 2016-12-17 09:59:29.180131

"""

# revision identifiers, used by Alembic.
revision = '10c63898a94e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('task_id', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Result')
    ### end Alembic commands ###
