"""empty message

Revision ID: d88e3fd4f24
Revises: 10c63898a94e
Create Date: 2016-12-17 10:05:01.191804

"""

# revision identifiers, used by Alembic.
revision = 'd88e3fd4f24'
down_revision = '10c63898a94e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Result', sa.Column('query', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Result', 'query')
    ### end Alembic commands ###
